// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeKtk65tSUQE78VqJ3DajnYTQMqufBhQ4',
    appId: '1:491300665165:web:180ffe63ffede8c3876904',
    messagingSenderId: '491300665165',
    projectId: 'codedevweb-c6cb0',
    authDomain: 'codedevweb-c6cb0.firebaseapp.com',
    databaseURL: 'https://codedevweb-c6cb0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codedevweb-c6cb0.appspot.com',
    measurementId: 'G-LV5MQ26QBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQMFWG9xlhbvyEI0oNddJjbO6F5M4BN-c',
    appId: '1:491300665165:android:dcf0902f29cb7f31876904',
    messagingSenderId: '491300665165',
    projectId: 'codedevweb-c6cb0',
    databaseURL: 'https://codedevweb-c6cb0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codedevweb-c6cb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfkl5rYFoEwyTc9wAeT6O5CzTj3eG28qM',
    appId: '1:491300665165:ios:8ed509dd02be4020876904',
    messagingSenderId: '491300665165',
    projectId: 'codedevweb-c6cb0',
    databaseURL: 'https://codedevweb-c6cb0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codedevweb-c6cb0.appspot.com',
    iosBundleId: 'com.taihen.dev.codedevweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfkl5rYFoEwyTc9wAeT6O5CzTj3eG28qM',
    appId: '1:491300665165:ios:8ed509dd02be4020876904',
    messagingSenderId: '491300665165',
    projectId: 'codedevweb-c6cb0',
    databaseURL: 'https://codedevweb-c6cb0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codedevweb-c6cb0.appspot.com',
    iosBundleId: 'com.taihen.dev.codedevweb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeKtk65tSUQE78VqJ3DajnYTQMqufBhQ4',
    appId: '1:491300665165:web:fe6108dd73048689876904',
    messagingSenderId: '491300665165',
    projectId: 'codedevweb-c6cb0',
    authDomain: 'codedevweb-c6cb0.firebaseapp.com',
    databaseURL: 'https://codedevweb-c6cb0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codedevweb-c6cb0.appspot.com',
    measurementId: 'G-8DYTGFSW2X',
  );
}
